POST http://localhost:3000/api/reservations
Content-Type: application/json

{
  "fullName": "John Doe",
  "email": "john.doe@example.com",
  "phone": "1234567890",
  "tent": "oasis",
  "dates": ["2024-05-01", "2024-05-03"],
  "numGuest": 3
}